server:
  port: ${PORT:2222}

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database: MYSQL

logging:
  level:
    org.springframework.security: TRACE

security:
#  user:
#    name: root
#    password: password
  oauth2:
    resource:
#      loadBalanced: true
      userInfoUri: http://localhost:9999/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/