server:
  port: ${PORT:9990}

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: root
    password: root

logging:
  level:
    org.springframework.security: TRACE

security:
  user:
    name: root
    password: root
  oauth2:
    client:
      client-id: acme
      client-secret: secret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/